USE [SIDAF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[selecionarFORNECEDOR]
AS
	-- SELECIONANDO O(S) FORNECEDOR(ES)
		SELECT * FROM [SIDAF].[dbo].[Fornecedor]