USE [SIDAF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[selecionarFORNECEDORporIE]
	-- INFORMAÇÃO DO FORNECEDOR
		@ie char
AS
	-- SELECIONANDO O(S) FORNECEDOR(ES) PELO IE
		SELECT * FROM [SIDAF].[dbo].[Fornecedor]
		WHERE ie = @ie