USE [SIDAF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[excluirFORNECEDOR]
	-- INFORMAÇÃO SOBRE O FORNECEDOR
		@IDFornecedor int
AS
	-- EXCLUINDO FORNECEDOR
		DELETE FROM Fornecedor
		WHERE IDFornecedor = @IDFornecedor
