USE [SIDAF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[selecionarFORNECEDORporCNPJ]
	-- INFORMAÇÃO DO FORNECEDOR
		@cnpj char
AS
	-- SELECIONANDO O(S) FORNECEDOR(ES) PELO CNPJ
		SELECT * FROM [SIDAF].[dbo].[Fornecedor]
		WHERE cnpj = @cnpj