USE [SIDAF]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[selecionarFORNECEDORporID]
	-- INFORMAÇÃO DO FORNECEDOR
		@IDFornecedor char
AS
	-- SELECIONANDO O(S) FORNECEDOR(ES) PELO ID
		SELECT * FROM [SIDAF].[dbo].[Fornecedor]
		WHERE IDFornecedor = @IDFornecedor